package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="ADMINISTRADOR"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Administrador  implements java.io.Serializable {


     private BigDecimal perIdPersona;
     private Persona persona;
     private String funcion;
     private String area;

    public Administrador() {
    }

	
    public Administrador(Persona persona) {
        this.persona = persona;
    }
    public Administrador(Persona persona, String funcion, String area) {
       this.persona = persona;
       this.funcion = funcion;
       this.area = area;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="persona"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="PER_ID_PERSONA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPerIdPersona() {
        return this.perIdPersona;
    }
    
    public void setPerIdPersona(BigDecimal perIdPersona) {
        this.perIdPersona = perIdPersona;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="FUNCION", length=30)
    public String getFuncion() {
        return this.funcion;
    }
    
    public void setFuncion(String funcion) {
        this.funcion = funcion;
    }

    
    @Column(name="AREA", length=30)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }




}


