package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Aprendiz generated by hbm2java
 */
@Entity
@Table(name="APRENDIZ"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Aprendiz  implements java.io.Serializable {


     private BigDecimal perIdPersona;
     private Ficha ficha;
     private Persona persona;
     private String telAcudiente;
     private String nomAcudiente;
     private BigDecimal codigo;

    public Aprendiz() {
    }

	
    public Aprendiz(Ficha ficha, Persona persona) {
        this.ficha = ficha;
        this.persona = persona;
    }
    public Aprendiz(Ficha ficha, Persona persona, String telAcudiente, String nomAcudiente, BigDecimal codigo) {
       this.ficha = ficha;
       this.persona = persona;
       this.telAcudiente = telAcudiente;
       this.nomAcudiente = nomAcudiente;
       this.codigo = codigo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="persona"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="PER_ID_PERSONA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPerIdPersona() {
        return this.perIdPersona;
    }
    
    public void setPerIdPersona(BigDecimal perIdPersona) {
        this.perIdPersona = perIdPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FIC_CODIGO", nullable=false)
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="TEL_ACUDIENTE", length=20)
    public String getTelAcudiente() {
        return this.telAcudiente;
    }
    
    public void setTelAcudiente(String telAcudiente) {
        this.telAcudiente = telAcudiente;
    }

    
    @Column(name="NOM_ACUDIENTE", length=30)
    public String getNomAcudiente() {
        return this.nomAcudiente;
    }
    
    public void setNomAcudiente(String nomAcudiente) {
        this.nomAcudiente = nomAcudiente;
    }

    
    @Column(name="CODIGO", precision=22, scale=0)
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }




}


