package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="CATEGORIA"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Categoria  implements java.io.Serializable {


     private BigDecimal idCategoria;
     private String nombre;
     private Set<Elemento> elementos = new HashSet<Elemento>(0);

    public Categoria() {
    }

	
    public Categoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(BigDecimal idCategoria, String nombre, Set<Elemento> elementos) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
       this.elementos = elementos;
    }
   
     @Id 

    
    @Column(name="ID_CATEGORIA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set<Elemento> getElementos() {
        return this.elementos;
    }
    
    public void setElementos(Set<Elemento> elementos) {
        this.elementos = elementos;
    }




}


