package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Elemento generated by hbm2java
 */
@Entity
@Table(name="ELEMENTO"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Elemento  implements java.io.Serializable {


     private BigDecimal idElemento;
     private Categoria categoria;
     private Persona persona;
     private BigDecimal codigo;
     private String serial;
     private String marca;
     private Date fechaRegistro;
     private BigDecimal idCategoria;
     private String numDocumento;

    public Elemento() {
    }

	
    public Elemento(BigDecimal idElemento, Categoria categoria) {
        this.idElemento = idElemento;
        this.categoria = categoria;
    }
    public Elemento(BigDecimal idElemento, Categoria categoria, Persona persona, BigDecimal codigo, String serial, String marca, Date fechaRegistro, BigDecimal idCategoria, String numDocumento) {
       this.idElemento = idElemento;
       this.categoria = categoria;
       this.persona = persona;
       this.codigo = codigo;
       this.serial = serial;
       this.marca = marca;
       this.fechaRegistro = fechaRegistro;
       this.idCategoria = idCategoria;
       this.numDocumento = numDocumento;
    }
   
     @Id 

    
    @Column(name="ID_ELEMENTO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdElemento() {
        return this.idElemento;
    }
    
    public void setIdElemento(BigDecimal idElemento) {
        this.idElemento = idElemento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CAT_ID_CATEGORIA", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA")
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="CODIGO", precision=22, scale=0)
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="SERIAL", length=30)
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }

    
    @Column(name="MARCA", length=30)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_REGISTRO", length=7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    
    @Column(name="ID_CATEGORIA", precision=22, scale=0)
    public BigDecimal getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="NUM_DOCUMENTO", length=30)
    public String getNumDocumento() {
        return this.numDocumento;
    }
    
    public void setNumDocumento(String numDocumento) {
        this.numDocumento = numDocumento;
    }




}


