package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ficha generated by hbm2java
 */
@Entity
@Table(name="FICHA"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Ficha  implements java.io.Serializable {


     private BigDecimal codigo;
     private String nombre;
     private String horas;
     private String sede;
     private String instructores;
     private Set<Aprendiz> aprendizs = new HashSet<Aprendiz>(0);

    public Ficha() {
    }

	
    public Ficha(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Ficha(BigDecimal codigo, String nombre, String horas, String sede, String instructores, Set<Aprendiz> aprendizs) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.horas = horas;
       this.sede = sede;
       this.instructores = instructores;
       this.aprendizs = aprendizs;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="HORAS", length=0)
    public String getHoras() {
        return this.horas;
    }
    
    public void setHoras(String horas) {
        this.horas = horas;
    }

    
    @Column(name="SEDE", length=30)
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }

    
    @Column(name="INSTRUCTORES", length=30)
    public String getInstructores() {
        return this.instructores;
    }
    
    public void setInstructores(String instructores) {
        this.instructores = instructores;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ficha")
    public Set<Aprendiz> getAprendizs() {
        return this.aprendizs;
    }
    
    public void setAprendizs(Set<Aprendiz> aprendizs) {
        this.aprendizs = aprendizs;
    }




}


