package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Instructor generated by hbm2java
 */
@Entity
@Table(name="INSTRUCTOR"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Instructor  implements java.io.Serializable {


     private BigDecimal perIdPersona;
     private Persona persona;
     private String campo;

    public Instructor() {
    }

	
    public Instructor(Persona persona) {
        this.persona = persona;
    }
    public Instructor(Persona persona, String campo) {
       this.persona = persona;
       this.campo = campo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="persona"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="PER_ID_PERSONA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPerIdPersona() {
        return this.perIdPersona;
    }
    
    public void setPerIdPersona(BigDecimal perIdPersona) {
        this.perIdPersona = perIdPersona;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="CAMPO", length=30)
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }




}


