package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="VEHICULO"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private Persona persona;
     private String clase;
     private String modelo;
     private BigDecimal dias;
     private String horas;

    public Vehiculo() {
    }

	
    public Vehiculo(String placa) {
        this.placa = placa;
    }
    public Vehiculo(String placa, Persona persona, String clase, String modelo, BigDecimal dias, String horas) {
       this.placa = placa;
       this.persona = persona;
       this.clase = clase;
       this.modelo = modelo;
       this.dias = dias;
       this.horas = horas;
    }
   
     @Id 

    
    @Column(name="PLACA", unique=true, nullable=false, length=30)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA")
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="CLASE", length=30)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="MODELO", length=30)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="DIAS", precision=22, scale=0)
    public BigDecimal getDias() {
        return this.dias;
    }
    
    public void setDias(BigDecimal dias) {
        this.dias = dias;
    }

    
    @Column(name="HORAS", length=30)
    public String getHoras() {
        return this.horas;
    }
    
    public void setHoras(String horas) {
        this.horas = horas;
    }




}


