package entity;
// Generated 22/11/2017 08:55:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Vigilante generated by hbm2java
 */
@Entity
@Table(name="VIGILANTE"
    ,schema="ADMIN_PROYECTOSINRE"
)
public class Vigilante  implements java.io.Serializable {


     private BigDecimal perIdPersona;
     private Persona persona;
     private String turno;
     private String porteria;

    public Vigilante() {
    }

	
    public Vigilante(Persona persona) {
        this.persona = persona;
    }
    public Vigilante(Persona persona, String turno, String porteria) {
       this.persona = persona;
       this.turno = turno;
       this.porteria = porteria;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="persona"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="PER_ID_PERSONA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPerIdPersona() {
        return this.perIdPersona;
    }
    
    public void setPerIdPersona(BigDecimal perIdPersona) {
        this.perIdPersona = perIdPersona;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="TURNO", length=30)
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }

    
    @Column(name="PORTERIA", length=30)
    public String getPorteria() {
        return this.porteria;
    }
    
    public void setPorteria(String porteria) {
        this.porteria = porteria;
    }




}


